In [4]:
import requests
from bs4 import BeautifulSoup as BS
from IPython.core.display import HTML
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [6]:
href = ['/title/tt0111161/', '/title/tt0068646/', '/title/tt0468569/', '/title/tt0071562/', '/title/tt0050083/', '/title/tt0108052/', '/title/tt0167260/', '/title/tt0110912/', '/title/tt0120737/', '/title/tt0060196/', '/title/tt0109830/', '/title/tt0137523/', '/title/tt0167261/', '/title/tt1375666/', '/title/tt0080684/', '/title/tt0133093/', '/title/tt0099685/', '/title/tt0073486/', '/title/tt0114369/', '/title/tt0047478/', '/title/tt0038650/', '/title/tt0102926/', '/title/tt0317248/', '/title/tt0120815/', '/title/tt0118799/', '/title/tt0816692/', '/title/tt0120689/', '/title/tt0076759/', '/title/tt0103064/', '/title/tt0088763/', '/title/tt0245429/', '/title/tt0054215/', '/title/tt0253474/', '/title/tt6751668/', '/title/tt0110413/', '/title/tt0110357/', '/title/tt0172495/', '/title/tt0120586/', '/title/tt0407887/', '/title/tt0114814/', '/title/tt0482571/', '/title/tt2582802/', '/title/tt0034583/', '/title/tt0056058/', '/title/tt1675434/', '/title/tt0095327/', '/title/tt0027977/', '/title/tt0064116/', '/title/tt0047396/', '/title/tt0095765/', '/title/tt0078748/', '/title/tt0021749/', '/title/tt0078788/', '/title/tt0209144/', '/title/tt0082971/', '/title/tt1853728/', '/title/tt0910970/', '/title/tt0405094/', '/title/tt0043014/', '/title/tt0050825/', '/title/tt0032553/', '/title/tt0081505/', '/title/tt4154756/', '/title/tt0051201/', '/title/tt0090605/', '/title/tt4633694/', '/title/tt0169547/', '/title/tt0057012/', '/title/tt1345836/', '/title/tt0364569/', '/title/tt0086879/', '/title/tt7286456/', '/title/tt0361748/', '/title/tt2380307/', '/title/tt0114709/', '/title/tt0112573/', '/title/tt0082096/', '/title/tt4154796/', '/title/tt0119698/', '/title/tt0087843/', '/title/tt0119217/', '/title/tt1745960/', '/title/tt5311514/', '/title/tt0180093/', '/title/tt1187043/', '/title/tt0045152/', '/title/tt0435761/', '/title/tt0057565/', '/title/tt0086190/', '/title/tt8267604/', '/title/tt0062622/', '/title/tt0338013/', '/title/tt0105236/', '/title/tt2106476/', '/title/tt0091251/', '/title/tt0033467/', '/title/tt0022100/', '/title/tt0056172/', '/title/tt0053125/', '/title/tt0052357/', '/title/tt0211915/', '/title/tt0066921/', '/title/tt0053604/', '/title/tt0044741/', '/title/tt0036775/', '/title/tt0093058/', '/title/tt8503618/', '/title/tt0086250/', '/title/tt0070735/', '/title/tt0056592/', '/title/tt1255953/', '/title/tt1049413/', '/title/tt0113277/', '/title/tt0075314/', '/title/tt1832382/', '/title/tt0017136/', '/title/tt0119488/', '/title/tt0208092/', '/title/tt0095016/', '/title/tt0040522/', '/title/tt0097576/', '/title/tt0986264/', '/title/tt8579674/', '/title/tt0363163/', '/title/tt0059578/', '/title/tt5074352/', '/title/tt0372784/', '/title/tt0012349/', '/title/tt0053291/', '/title/tt10272386/', '/title/tt0042192/', '/title/tt6966692/', '/title/tt0993846/', '/title/tt0055031/', '/title/tt0089881/', '/title/tt0112641/', '/title/tt0457430/', '/title/tt0105695/', '/title/tt0469494/', '/title/tt0120382/', '/title/tt0167404/', '/title/tt0268978/', '/title/tt10872600/', '/title/tt0055630/', '/title/tt1130884/', '/title/tt0071853/', '/title/tt0040897/', '/title/tt0107290/', '/title/tt0057115/', '/title/tt0042876/', '/title/tt0266697/', '/title/tt0477348/', '/title/tt0266543/', '/title/tt0084787/', '/title/tt0080678/', '/title/tt0071315/', '/title/tt0081398/', '/title/tt0031381/', '/title/tt0434409/', '/title/tt2096673/', '/title/tt0120735/', '/title/tt0046912/', '/title/tt1305806/', '/title/tt0347149/', '/title/tt0050212/', '/title/tt5027774/', '/title/tt0117951/', '/title/tt1291584/', '/title/tt0116282/', '/title/tt1205489/', '/title/tt1392214/', '/title/tt0096283/', '/title/tt0264464/', '/title/tt0405159/', '/title/tt0118849/', '/title/tt0015864/', '/title/tt0083658/', '/title/tt0047296/', '/title/tt0112471/', '/title/tt2024544/', '/title/tt1201607/', '/title/tt0052618/', '/title/tt0050986/', '/title/tt2267998/', '/title/tt0041959/', '/title/tt0017925/', '/title/tt2278388/', '/title/tt0077416/', '/title/tt0107207/', '/title/tt0046268/', '/title/tt0072684/', '/title/tt4729430/', '/title/tt2119532/', '/title/tt0031679/', '/title/tt0015324/', '/title/tt0353969/', '/title/tt3011894/', '/title/tt0050976/', '/title/tt3170832/', '/title/tt1392190/', '/title/tt0978762/', '/title/tt0892769/', '/title/tt0118715/', '/title/tt0198781/', '/title/tt0073195/', '/title/tt0097165/', '/title/tt0019254/', '/title/tt0046438/', '/title/tt0395169/', '/title/tt1950186/', '/title/tt0075148/', '/title/tt0091763/', '/title/tt0092005/', '/title/tt1895587/', '/title/tt0088247/', '/title/tt3315342/', '/title/tt0382932/', '/title/tt1979320/', '/title/tt0048473/', '/title/tt0074958/', '/title/tt0758758/', '/title/tt0032138/', '/title/tt0381681/', '/title/tt0107048/', '/title/tt0070047/', '/title/tt0036868/', '/title/tt0317705/', '/title/tt0035446/', '/title/tt0058946/', '/title/tt15097216/', '/title/tt1028532/', '/title/tt0113247/', '/title/tt0476735/', '/title/tt0325980/', '/title/tt0032551/', '/title/tt0245712/', '/title/tt0032976/', '/title/tt0061512/', '/title/tt6710474/', '/title/tt0053198/', '/title/tt4016934/', '/title/tt0025316/', '/title/tt0060827/', '/title/tt0059742/', '/title/tt0079470/', '/title/tt0071411/', '/title/tt0103639/', '/title/tt1454029/', '/title/tt0129167/', '/title/tt0083987/']

In [7]:
score_id = ['07041', '07042', '07043', '07044', '07045', '07046', '07047', '07048', '07049', '070410', '070411', '070412', '070413', '070414', '070415', '070416', '070417', '070418', '070419', '070420', '070421', '070422', '070423', '070424', '070425', '070426', '070427', '070428', '070429', '070430', '070431', '070432', '070433', '070434', '070435', '070436', '070437', '070438', '070439', '070440', '070441', '070442', '070443', '070444', '070445', '070446', '070447', '070448', '070449', '070450', '070451', '070452', '070453', '070454', '070455', '070456', '070457', '070458', '070459', '070460', '070461', '070462', '070463', '070464', '070465', '070466', '070467', '070468', '070469', '070470', '070471', '070472', '070473', '070474', '070475', '070476', '070477', '070478', '070479', '070480', '070481', '070482', '070483', '070484', '070485', '070486', '070487', '070488', '070489', '070490', '070491', '070492', '070493', '070494', '070495', '070496', '070497', '070498', '070499', '0704100', '0704101', '0704102', '0704103', '0704104', '0704105', '0704106', '0704107', '0704108', '0704109', '0704110', '0704111', '0704112', '0704113', '0704114', '0704115', '0704116', '0704117', '0704118', '0704119', '0704120', '0704121', '0704122', '0704123', '0704124', '0704125', '0704126', '0704127', '0704128', '0704129', '0704130', '0704131', '0704132', '0704133', '0704134', '0704135', '0704136', '0704137', '0704138', '0704139', '0704140', '0704141', '0704142', '0704143', '0704144', '0704145', '0704146', '0704147', '0704148', '0704149', '0704150', '0704151', '0704152', '0704153', '0704154', '0704155', '0704156', '0704157', '0704158', '0704159', '0704160', '0704161', '0704162', '0704163', '0704164', '0704165', '0704166', '0704167', '0704168', '0704169', '0704170', '0704171', '0704172', '0704173', '0704174', '0704175', '0704176', '0704177', '0704178', '0704179', '0704180', '0704181', '0704182', '0704183', '0704184', '0704185', '0704186', '0704187', '0704188', '0704189', '0704190', '0704191', '0704192', '0704193', '0704194', '0704195', '0704196', '0704197', '0704198', '0704199', '0704200', '0704201', '0704202', '0704203', '0704204', '0704205', '0704206', '0704207', '0704208', '0704209', '0704210', '0704211', '0704212', '0704213', '0704214', '0704215', '0704216', '0704217', '0704218', '0704219', '0704220', '0704221', '0704222', '0704223', '0704224', '0704225', '0704226', '0704227', '0704228', '0704229', '0704230', '0704231', '0704232', '0704233', '0704234', '0704235', '0704236', '0704237', '0704238', '0704239', '0704240', '0704241', '0704242', '0704243', '0704244', '0704245', '0704246', '0704247', '0704248', '0704249', '0704250']

#### For Loop to Access IMDb Score

In [9]:
headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0'
}

In [12]:
score = []
for x in href:
    try: 
        IMDb_soup = BS(requests.get(f'https://www.imdb.com{x}ratings/?ref_=tt_ov_rt', headers = headers).text)
        score.append(IMDb_soup.findAll('span', attrs ={'class':'ipl-rating-star__rating'})[0].text)
    except:
        score.append("Not Available on IMDb")

In [17]:
score

['9.3',
 '9.2',
 '9',
 '9',
 '9',
 '9',
 '9',
 '8.9',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.5',
 '8.6',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.6',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.3',
 '8.4',
 '8.3',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.3',
 '8.3',
 '8.4',
 '8.4',
 '8.3',
 '8.4',
 '8.3',
 '8.3',
 '8.4',
 '8.3',
 '8.4',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.4',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.4',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.2',
 '8.3',
 '8.3',
 '8.2',
 '8.2',
 '8.2',
 '8.3',
 '8.2',
 '8.4',
 '8.2',
 '8.2',
 '8.2',
 '8.3',
 '8.2',
 '8.3',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.3',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.3',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.2',
 '8.1',
 '8.1',
 '8.2',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.2',
 '8.2',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.2',
 '8.1',
 '8.1',
 '8.1',
 '8.2',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.2',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.2',
 '8.2',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.3',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8',
 '8.2',
 '8.1',
 '8.9',
 '8.1',
 '8.1',
 '8.2',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8.1',
 '8',
 '8.2',
 '8',
 '8.1',
 '8.1',
 '8.1']

#### Audience Reviews

In [36]:
reviews = []
for x in href:
    try: 
        IMDb_soup = BS(requests.get(f'https://www.imdb.com{x}ratings/?ref_=tt_ov_rt', headers = headers).text)
        reviews.append(IMDb_soup.findAll('div', attrs ={'class':'smallcell'})[0].text.replace('\n','').strip(' ').replace(',',''))
    except:
        reviews.append("Not Available on IMDb")

In [43]:
reviews

['2666904',
 '1848055',
 '2639814',
 '1265636',
 '787589',
 '1350290',
 '1838370',
 '2041472',
 '1867531',
 '759951',
 '2067290',
 '2112335',
 '1660000',
 '2339460',
 '1287765',
 '1905329',
 '1155986',
 '1005471',
 '1644018',
 '345954',
 '455195',
 '1426876',
 '755530',
 '1386058',
 '693325',
 '1814208',
 '1295961',
 '1360313',
 '1095653',
 '1199895',
 '760232',
 '671011',
 '829310',
 '794632',
 '1157139',
 '1054445',
 '1494451',
 '1119810',
 '1320443',
 '1082774',
 '1328176',
 '854465',
 '571165',
 '57449',
 '855309',
 '277235',
 '242865',
 '329532',
 '491570',
 '261344',
 '880274',
 '185213',
 '666471',
 '1234730',
 '963582',
 '1545522',
 '1112627',
 '389966',
 '222496',
 '197950',
 '224458',
 '1019113',
 '1073540',
 '126031',
 '716738',
 '525106',
 '1153043',
 '491182',
 '1698754',
 '578590',
 '401433',
 '1271542',
 '1441883',
 '505337',
 '991158',
 '1036160',
 '251623',
 '1121735',
 '394495',
 '352345',
 '964522',
 '437923',
 '267838',
 '840557',
 '400332',
 '243017',
 '834691',
 '45421',
 '1051097',
 '89985',
 '668047',
 '1005277',
 '1015402',
 '330325',
 '80404',
 '442450',
 '158657',
 '294407',
 '328626',
 '402707',
 '756338',
 '828890',
 '182216',
 '79096',
 '158059',
 '742000',
 '94597',
 '838839',
 '262911',
 '317270',
 '178257',
 '1041124',
 '653875',
 '829740',
 '245668',
 '175018',
 '583276',
 '855004',
 '874791',
 '164198',
 '753693',
 '194001',
 '585459',
 '356447',
 '257414',
 '191641',
 '1465947',
 '127016',
 '267966',
 '152917',
 '131993',
 '489416',
 '1400359',
 '78207',
 '126310',
 '520067',
 '669074',
 '412667',
 '586402',
 '1076754',
 '990654',
 '931211',
 '747321',
 '123563',
 '1307341',
 '541871',
 '125611',
 '985933',
 '245253',
 '169301',
 '1112584',
 '970111',
 '1041427',
 '425728',
 '242057',
 '327382',
 '354736',
 '316204',
 '1120640',
 '711774',
 '582434',
 '176752',
 '210401',
 '395066',
 '221543',
 '506179',
 '687065',
 '472955',
 '677850',
 '775538',
 '709113',
 '339484',
 '978036',
 '687359',
 '75314',
 '111993',
 '768621',
 '155903',
 '308728',
 '700579',
 '872691',
 '239988',
 '108005',
 '979544',
 '172429',
 '92071',
 '806965',
 '340095',
 '175912',
 '61751',
 '168813',
 '150155',
 '524558',
 '116285',
 '50588',
 '184695',
 '199080',
 '185969',
 '420974',
 '999407',
 '177885',
 '739216',
 '807775',
 '907225',
 '606161',
 '490581',
 '55397',
 '62257',
 '356380',
 '392172',
 '575692',
 '415018',
 '404333',
 '470069',
 '863721',
 '761147',
 '734739',
 '480240',
 '33433',
 '160391',
 '623467',
 '400453',
 '264893',
 '631136',
 '408898',
 '65152',
 '736176',
 '37911',
 '60722',
 '201593',
 '285656',
 '174571',
 '87164',
 '1124741',
 '93874',
 '241243',
 '137984',
 '178109',
 '244424',
 '118731',
 '147913',
 '104688',
 '119489',
 '235193',
 '400445',
 '30180',
 '420110',
 '459794',
 '198891',
 '232396']

#### US User Reviews

In [50]:
usa = []
for x in href:
    try: 
        IMDb_soup = BS(requests.get(f'https://www.imdb.com{x}ratings/?ref_=tt_ov_rt', headers = headers).text)
        usa.append(IMDb_soup.findAll('div', attrs ={'class':'smallcell'})[16].find('a').text.replace('\n','').strip(' ').replace(',',''))
    except:
        usa.append("Not Available on IMDb")

In [53]:
len(usa)

250

In [54]:
intl = []
for x in href:
    try: 
        IMDb_soup = BS(requests.get(f'https://www.imdb.com{x}ratings/?ref_=tt_ov_rt', headers = headers).text)
        intl.append(IMDb_soup.findAll('div', attrs ={'class':'smallcell'})[17].find('a').text.replace('\n','').strip(' ').replace(',',''))
    except:
        intl.append("Not Available on IMDb")

In [55]:
intl

['1672983',
 '1161734',
 '1646769',
 '805848',
 '509017',
 '865722',
 '1171402',
 '1280206',
 '1182624',
 '491783',
 '1309154',
 '1358803',
 '1062584',
 '1542687',
 '760493',
 '1209256',
 '715615',
 '637995',
 '1085250',
 '210577',
 '232439',
 '898344',
 '527568',
 '867521',
 '490502',
 '1257901',
 '868547',
 '792380',
 '690564',
 '748169',
 '516369',
 '410701',
 '588486',
 '626228',
 '802155',
 '666829',
 '964570',
 '734530',
 '856075',
 '684358',
 '904870',
 '618807',
 '324326',
 '41932',
 '670168',
 '195234',
 '167319',
 '221563',
 '295066',
 '182528',
 '550200',
 '122027',
 '411303',
 '803875',
 '555151',
 '1039882',
 '731415',
 '294701',
 '127995',
 '126924',
 '157008',
 '651505',
 '774915',
 '82086',
 '438883',
 '375965',
 '727585',
 '282667',
 '1076289',
 '418640',
 '244032',
 '992405',
 '985783',
 '369873',
 '615234',
 '643886',
 '167071',
 '827662',
 '263484',
 '249998',
 '609189',
 '310590',
 '209553',
 '562780',
 '285891',
 '135052',
 '532493',
 '28910',
 '630839',
 '78797',
 '413809',
 '666223',
 '652994',
 '265012',
 '57176',
 '246620',
 '96318',
 '174612',
 '185177',
 '248220',
 '527163',
 '530064',
 '111885',
 '47048',
 '86428',
 '464388',
 '51972',
 '557321',
 '152605',
 '159307',
 '141497',
 '684473',
 '433205',
 '550780',
 '177107',
 '107934',
 '369086',
 '589223',
 '540716',
 '108426',
 '448392',
 '141800',
 '455374',
 '267805',
 '171947',
 '143604',
 '935769',
 '87356',
 '162851',
 '128148',
 '71570',
 '401704',
 '976469',
 '47694',
 '77720',
 '330676',
 '445833',
 '250543',
 '371773',
 '719219',
 '615755',
 '627491',
 '554824',
 '73218',
 '928404',
 '304256',
 '65619',
 '603925',
 '147399',
 '103205',
 '734173',
 '634776',
 '663008',
 '266098',
 '158131',
 '196594',
 '217212',
 '174650',
 '743746',
 '498412',
 '411087',
 '111408',
 '165426',
 '272402',
 '129728',
 '390322',
 '475403',
 '328118',
 '407141',
 '511528',
 '521933',
 '237276',
 '677381',
 '464302',
 '54088',
 '72611',
 '489296',
 '83664',
 '223896',
 '500910',
 '584343',
 '147202',
 '71654',
 '697910',
 '101303',
 '53983',
 '582245',
 '213856',
 '126138',
 '39330',
 '111871',
 '118814',
 '391729',
 '49795',
 '32805',
 '142134',
 '164105',
 '121843',
 '310093',
 '698776',
 '131865',
 '495315',
 '508855',
 '574594',
 '350871',
 '321399',
 '31639',
 '40123',
 '228815',
 '294546',
 '361059',
 '253546',
 '230961',
 '342647',
 '545963',
 '543695',
 '493219',
 '358951',
 '22747',
 '91170',
 '443105',
 '186253',
 '192787',
 '388014',
 '248902',
 '29803',
 '465191',
 '23903',
 '37177',
 '182490',
 '218035',
 '135231',
 '67634',
 '717122',
 '45767',
 '172212',
 '82365',
 '85875',
 '169898',
 '76013',
 '117301',
 '54241',
 '82634',
 '125534',
 '275106',
 '21821',
 '255681',
 '291994',
 '114574',
 '143466']

#### Females Reviews (all ages)

In [62]:
f_rev = []
for x in href:
    try: 
        IMDb_soup = BS(requests.get(f'https://www.imdb.com{x}ratings/?ref_=tt_ov_rt', headers = headers).text)
        f_rev.append(IMDb_soup.findAll('div', attrs ={'class':'smallcell'})[10].find('a').text.replace('\n','').strip(' ').replace(',',''))
    except:
        f_rev.append("Not Available on IMDb")

In [69]:
len(f_rev)

250

#### Female Overall Score

In [81]:
f_score = []
for x in href:
    try: 
        IMDb_soup = BS(requests.get(f'https://www.imdb.com{x}ratings/?ref_=tt_ov_rt', headers = headers).text)
        f_score.append(IMDb_soup.findAll('div', attrs ={'class':'bigcell'})[10].text)
    except:
        f_score.append("Not Available on IMDb")

In [82]:
len(f_score)

250

#### Male Reviews (all ages)

In [71]:
m_rev = []
for x in href:
    try: 
        IMDb_soup = BS(requests.get(f'https://www.imdb.com{x}ratings/?ref_=tt_ov_rt', headers = headers).text)
        m_rev.append(IMDb_soup.findAll('div', attrs ={'class':'smallcell'})[5].find('a').text.replace('\n','').strip(' ').replace(',',''))
    except:
        m_rev.append("Not Available on IMDb")

In [73]:
len(m_rev)

250

#### Male Overall Score

In [77]:
m_score = []
for x in href:
    try: 
        IMDb_soup = BS(requests.get(f'https://www.imdb.com{x}ratings/?ref_=tt_ov_rt', headers = headers).text)
        m_score.append(IMDb_soup.findAll('div', attrs ={'class':'bigcell'})[5].text)
    except:
        m_score.append("Not Available on IMDb")

In [78]:
len(m_score)

250

In [80]:
#males_score
test = BS(requests.get(f'https://www.imdb.com/title/tt0111161/ratings/?ref_=tt_ov_r', headers = headers).text)
test.findAll('div', attrs ={'class':'bigcell'})[5].text

'9.2'

#### DataFrame Conversion

In [83]:
table = {'Score_ID':score_id, 'IMDb_Score':score, 'Audience_Reviews': reviews, 'US_Users': usa, 'Non_US_Users':intl, 'Male_Reviews':m_rev, 'Female_Reviews':f_rev, 'Male_Score':m_score, 'Female_Score':f_score}

IMDb_Score = pd.DataFrame(table, columns=['Score_ID','IMDb_Score', 'Audience_Reviews', 'US_Users', 'Non_US_Users', 'Male_Reviews', 'Female_Reviews','Male_Score','Female_Score'])

IMDb_Score

,Score_ID,IMDb_Score,Audience_Reviews,US_Users,Non_US_Users,Male_Reviews,Female_Reviews,Male_Score,Female_Score
0,07041,9.3,2666904,566032,1672983,1475251,294889,9.3,9.2
1,07042,9.2,1848055,417566,1161734,1072921,166441,9.2,8.9
2,07043,9,2639814,621027,1646769,1490958,267216,9.0,8.7
3,07044,9,1265636,282291,805848,759883,105690,9.0,8.7
4,07045,9,787589,187528,509017,453568,76860,9.0,8.9
...,...,...,...,...,...,...,...,...,...
245,0704246,8.2,30180,5700,21821,20674,2229,8.2,8.3
246,0704247,8,420110,122753,255681,214214,81695,8.0,8.2
247,0704248,8.1,459794,114135,291994,210785,137209,7.9,8.4
248,0704249,8.1,198891,64218,114574,120961,22987,8.0,8.0
249,0704250,8.1,232396,55588,143466,150392,25132,8.1,8.0

In [84]:
IMDb_Score.to_csv('../Data/IMDb_Score.csv')